# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPNWXdz2fDXR7fF-cDO3DL1LFTvGFKbU
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import torch
from torchvision import transforms as T
from PIL import Image
import timm
import io
import base64
import os

app = Flask(__name__)
CORS(app)

# Class names
class_names = [
    "metal waste",
    "organic waste",
    "paper waste",
    "plastic waste",
    "battery waste",
    "white-glass",
    "trash",
    "green-glass",
    "E-waste",
    "clothing waste",
    "cardboard waste",
    "brown-glass"
]

# Image transform
transform = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
])

# Load model function
def load_model(model_name, weight_path):
    model = timm.create_model(model_name, pretrained=False, num_classes=len(class_names))
    state = torch.load(weight_path, map_location="cpu")
    model.load_state_dict(state)
    model.eval()
    return model

# Load models once
models = {
    "mobilenet": load_model("mobilenetv3_large_100", "mobilenet.pth"),
    "rexnet": load_model("rexnet_150", "rexnet.pth")
}

@app.get("/")
def home():
    return "🔥 Waste Classifier API running on Render!"

# Convert Base64 → bytes
def base64_to_bytes(data_url):
    header, encoded = data_url.split(",", 1)
    return base64.b64decode(encoded)

@app.post("/predict")
def predict():
    try:
        data = request.get_json()

        if "image" not in data:
            return jsonify({"error": "No image provided"}), 400

        img_bytes = io.BytesIO(base64_to_bytes(data["image"]))
        img = Image.open(img_bytes).convert("RGB")
        img_tensor = transform(img).unsqueeze(0)

        # Run both models
        results = {}
        for name, model in models.items():
            with torch.no_grad():
                logits = model(img_tensor)
                probs = torch.softmax(logits, dim=1)
                conf, idx = torch.max(probs, 1)

            results[name] = {
                "prediction": class_names[idx.item()],
                "confidence": float(conf.item())
            }

        return jsonify(results)

    except Exception as e:
        print("Prediction Error:", e)
        return jsonify({"error": str(e)}), 500

# Run normally (Render will execute this)
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)