services:
  - type: web
    name: recycling-ai-backend
    env: python
    plan: free

    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app --chdir backend --timeout 0

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

    disk:
      name: model_files
      mountPath: /opt/render/project/src/backend
      sizeGB: 2
